[build.environment]
  NPM_FLAGS = "--version"
  NODE_VERSION = "16"

[build]
  publish = "/code/dist"
  command = "cd code && npx pnpm i --store=node_modules/.pnpm-store && npx pnpm run generate"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
